=== mojohaus/taglist-maven-plugin/xsd/TaglistOutput-1.0.0.xsd
<?xml version="1.0"?>
<!-- =================== DO NOT EDIT THIS FILE ====================         -->
<!-- Generated by Modello 1.11,                                             -->
<!-- any modifications will be overwritten.                                 -->
<!-- ==============================================================         -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns="org.codehaus.mojo.taglist-maven-plugin" targetNamespace="org.codehaus.mojo.taglist-maven-plugin">
  <xs:element name="report" type="TagListXMLReport">
    <xs:annotation>
      <xs:documentation source="version">1.0.0</xs:documentation>
      <xs:documentation source="description">The TagList report in XML format.</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="TagListXMLReport">
    <xs:annotation>
      <xs:documentation source="version">1.0.0</xs:documentation>
      <xs:documentation source="description">The TagList report in XML format.</xs:documentation>
    </xs:annotation>
    <xs:all>
      <xs:element minOccurs="0" name="tags">
        <xs:annotation>
          <xs:documentation source="version">1.0.0</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="tag" minOccurs="0" maxOccurs="unbounded" type="TagListXMLTag"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>
  <xs:complexType name="TagListXMLTag">
    <xs:annotation>
      <xs:documentation source="version">1.0.0</xs:documentation>
      <xs:documentation source="description">A specific tag defined by the user.</xs:documentation>
    </xs:annotation>
    <xs:all>
      <xs:element minOccurs="0" name="files">
        <xs:annotation>
          <xs:documentation source="version">1.0.0</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="file" minOccurs="0" maxOccurs="unbounded" type="TagListXMLFile"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
    <xs:attribute name="name" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation source="version">1.0.0</xs:documentation>
        <xs:documentation source="description">The name of the tag.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="count" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation source="version">1.0.0</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="TagListXMLFile">
    <xs:annotation>
      <xs:documentation source="version">1.0.0</xs:documentation>
      <xs:documentation source="description">The file a tag was found within.</xs:documentation>
    </xs:annotation>
    <xs:all>
      <xs:element minOccurs="0" name="comments">
        <xs:annotation>
          <xs:documentation source="version">1.0.0</xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:sequence>
            <xs:element name="comment" minOccurs="0" maxOccurs="unbounded" type="TagListXMLComment"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
    <xs:attribute name="name" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation source="version">1.0.0</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="count" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation source="version">1.0.0</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="TagListXMLComment">
    <xs:annotation>
      <xs:documentation source="version">1.0.0</xs:documentation>
      <xs:documentation source="description">The comment a tag was found within.</xs:documentation>
    </xs:annotation>
    <xs:all>
      <xs:element minOccurs="0" name="lineNumber" type="xs:string">
        <xs:annotation>
          <xs:documentation source="version">1.0.0</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="comment" type="xs:string">
        <xs:annotation>
          <xs:documentation source="version">1.0.0</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:all>
  </xs:complexType>
</xs:schema>

=== mojohaus/taglist-maven-plugin/src/test/resources/unit/basic-config-test/expected-taglist.xml
<?xml version="1.0" encoding="UTF-8"?>
<report xsi:schemaLocation="https://www.mojohaus.org/TAGLISTOUTPUT/1.0.0 https://www.mojohaus.org/taglist-maven-plugin/xsd/taglistOutput-1.0.0.xsd"
        xmlns="https://www.mojohaus.org/TAGLISTOUTPUT/1.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <tags>
    <tag name="@create_output" count="1">
      <files>
        <file name="com.BasicConfig" count="1">
          <comments>
            <comment>
              <lineNumber>11</lineNumber>
              <comment>This is the tag for the output test.</comment>
            </comment>
          </comments>
        </file>
      </files>
    </tag>
  </tags>
</report>
